// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"slices"
	"strconv"
	"strings"
	"sync"

	"github.com/arran4/md2png/cmd"
	"github.com/arran4/md2png/cmd/md2png/templates"
	"github.com/arran4/md2png/internal/cli"
)

type Cmd interface {
	Execute(args []string) error
	Usage()
}

type InternalCommand struct {
	Exec      func(args []string) error
	UsageFunc func()
}

func (c *InternalCommand) Execute(args []string) error {
	return c.Exec(args)
}

func (c *InternalCommand) Usage() {
	c.UsageFunc()
}

func NewLazyCommand(f func() Cmd) func() Cmd {
	var once sync.Once
	var cmd Cmd
	return func() Cmd {
		once.Do(func() {
			cmd = f()
		})
		return cmd
	}
}

type UserError struct {
	Err error
	Msg string
}

func (e *UserError) Error() string {
	if e.Err != nil {
		return fmt.Sprintf("%s: %v", e.Msg, e.Err)
	}
	return e.Msg
}

func NewUserError(err error, msg string) *UserError {
	return &UserError{Err: err, Msg: msg}
}

func executeUsage(out io.Writer, templateName string, data any) error {
	return templates.GetTemplates().ExecuteTemplate(out, templateName, data)
}

type RootCmd struct {
	*flag.FlagSet
	Commands       map[string]func() Cmd
	Version        string
	Commit         string
	Date           string
	in             *string
	out            *string
	width          *int
	margin         *int
	pt             *float64
	theme          *string
	fontRegular    *string
	fontBold       *string
	fontMono       *string
	footnoteLinks  *bool
	footnoteImages *bool
	maxHeight      *int
	CommandAction  func(c *RootCmd) error
}

func (c *RootCmd) Usage() {
	err := executeUsage(os.Stderr, "md2png_usage.txt", UsageDataRootCmd{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *RootCmd) UsageRecursive() {
	err := executeUsage(os.Stderr, "md2png_usage.txt", UsageDataRootCmd{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

type UsageDataRootCmd struct {
	*RootCmd
	Recursive bool
}

func NewRoot(name, version, commit, date string) (*RootCmd, error) {
	c := &RootCmd{
		FlagSet:  flag.NewFlagSet(name, flag.ExitOnError),
		Commands: make(map[string]func() Cmd),
		Version:  version,
		Commit:   commit,
		Date:     date,
	}
	c.FlagSet.Usage = c.Usage

	c.Func("in", "flag: Input Markdown file ( if empty)", func(s string) error {
		c.in = &s
		return nil
	})

	c.Func("out", "flag: Output image file (.png, .jpg, or .gif)", func(s string) error {
		c.out = &s
		return nil
	})

	c.Func("width", "flag: Output image width in pixels (0 for default)", func(s string) error {
		parsed, err := strconv.Atoi(s)
		if err != nil {
			return err
		}
		val := parsed
		c.width = &val
		return nil
	})

	c.Func("margin", "flag: Margin in pixels (0 for default)", func(s string) error {
		parsed, err := strconv.Atoi(s)
		if err != nil {
			return err
		}
		val := parsed
		c.margin = &val
		return nil
	})

	c.Func("pt", "flag: Base font size in points (paragraph) (0 for default)", func(s string) error {
		parsed, err := strconv.ParseFloat(s, 64)
		if err != nil {
			return err
		}
		val := parsed
		c.pt = &val
		return nil
	})

	c.Func("theme", "flag: Theme: light|dark", func(s string) error {
		c.theme = &s
		return nil
	})

	c.Func("font", "flag: Path to TTF for regular text (optional; default Go Regular)", func(s string) error {
		c.fontRegular = &s
		return nil
	})

	c.Func("fontbold", "flag: Path to TTF for bold text (optional; default Go Bold)", func(s string) error {
		c.fontBold = &s
		return nil
	})

	c.Func("fontmono", "flag: Path to TTF for mono/code (optional; default Go Mono)", func(s string) error {
		c.fontMono = &s
		return nil
	})

	c.BoolFunc("footnote-links", "flag: Add footnotes for link destinations", func(s string) error {
		parsed, err := strconv.ParseBool(s)
		if err != nil {
			return err
		}
		val := parsed
		c.footnoteLinks = &val
		return nil
	})

	c.BoolFunc("footnote-images", "flag: Add footnotes for image destinations", func(s string) error {
		parsed, err := strconv.ParseBool(s)
		if err != nil {
			return err
		}
		val := parsed
		c.footnoteImages = &val
		return nil
	})

	c.Func("max-height", "flag: Maximum output height in pixels (0 for default)", func(s string) error {
		parsed, err := strconv.Atoi(s)
		if err != nil {
			return err
		}
		val := parsed
		c.maxHeight = &val
		return nil
	})

	c.CommandAction = func(c *RootCmd) error {

		err := cli.Md2png(c.in, c.out, c.width, c.margin, c.pt, c.theme, c.fontRegular, c.fontBold, c.fontMono, c.footnoteLinks, c.footnoteImages, c.maxHeight)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("md2png failed: %w", err)
		}
		return nil
	}

	c.Commands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					c.UsageRecursive()
					return nil
				}
				c.Usage()
				return nil
			},
			UsageFunc: c.Usage,
		}
	}
	c.Commands["version"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				fmt.Printf("Version: %s\nCommit: %s\nDate: %s\n", c.Version, c.Commit, c.Date)
				return nil
			},
			UsageFunc: func() {
				fmt.Fprintf(os.Stderr, "Usage: %s version\n", os.Args[0])
			},
		}
	}
	return c, nil
}

func (c *RootCmd) Execute(args []string) (err error) {
	var remainingArgs []string
	dashDashSeen := false
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			dashDashSeen = true
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "in":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				s := value
				c.in = &s

			case "out":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				s := value
				c.out = &s

			case "width":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.width = &iv

			case "margin":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.margin = &iv

			case "pt":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				f, err := strconv.ParseFloat(value, 64)
				if err != nil {
					return fmt.Errorf("invalid float64 value for flag %s: %s", name, value)
				}
				c.pt = &f

			case "theme":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				s := value
				c.theme = &s

			case "fontRegular", "font":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				s := value
				c.fontRegular = &s

			case "fontBold", "fontbold":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				s := value
				c.fontBold = &s

			case "fontMono", "fontmono":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				s := value
				c.fontMono = &s

			case "footnoteLinks", "footnote-links":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.footnoteLinks = &b
				} else {
					b := true
					c.footnoteLinks = &b
				}

			case "footnoteImages", "footnote-images":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.footnoteImages = &b
				} else {
					b := true
					c.footnoteImages = &b
				}

			case "maxHeight", "max-height":
				if !hasValue {
					if i+1 < len(args) {
						value = args[i+1]
						i++
					} else {
						return fmt.Errorf("flag %s requires a value", name)
					}
				}
				iv, err := strconv.Atoi(value)
				if err != nil {
					return fmt.Errorf("invalid integer value for flag %s: %s", name, value)
				}
				c.maxHeight = &iv
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}
	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("md2png failed: %w", err)
		}
	}

	if !dashDashSeen && len(remainingArgs) > 0 {
		if cmd, ok := c.Commands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	return nil
}
